---
- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yml.j2"
    dest: "/tmp/cluster-config.yml"
    mode: 0644
  tags:
    - copy-config-template

- name: Create kind cluster
  shell: "kind create cluster --name {{ cluster_name }} --config /tmp/cluster-config.yml"
  tags:
   - create-kind-cluster

- name: Cluster creation has been finished
  debug:
    msg: "Cluster creation of kind cluster {{ cluster_name }} has been finished."
  tags:
    - cluster-creation-finished