apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - services

configMapGenerator:
  - name: be
    envs:
      - configs/be.properties
  - name: content
    envs:
      - configs/content.properties
  - name: course
    envs:
      - configs/course.properties

secretGenerator:
  - envs:
      - secrets/database-credentials.properties
    name: database-credentials

generatorOptions:
  disableNameSuffixHash: true
