# https://artifacthub.io/packages/helm/bitnami/postgresql/16.6.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      # chart: postgresql
      chart: ./bitnami/postgresql
      version: "16.6.3"
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  interval: 3m
  install:
    remediation:
      retries: 3
  values:
    auth:
      enablePostgresUser: true
      existingSecret: "database-credentials"
      secretKeys:
        adminPasswordKey: "POSTGRES_PASSWORD"

    primary:
      initdb:
        scripts:
          initdb.sql: |
            CREATE DATABASE courses;
            CREATE DATABASE content;
