auth:
  username: myuser
  password: mypassword
  database: mydb

primary:
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 2Gi

# This is optional, but you can override resources or any other chart config
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m
