auth:
  username: user
  password: password
  database: mydb

primary:
  service:
    type: ClusterIP

ingress:
  enabled: true
  className: "nginx"
  annotations: {
                 'nginx.ingress.kubernetes.io/backend-protocol: "HTTP"',
                 'nginx.ingress.kubernetes.io/force-ssl-redirect: "true"',
                 'nginx.ingress.kubernetes.io/ssl-passthrough: "false"'
  }