---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-services
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1m
  retryInterval: 20s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: flux/infrastructure/services
  prune: true
