@startuml
left to right direction
skinparam packageStyle rectangle  
skinparam linetype ortho
skinparam package {
    FontSize 13
    FontStyle bold
}

actor Kid    as "Kid"
actor Parent as "Parent"
actor Admin  as "Administrator"

rectangle "Learning application for kids" {

  package "Auth" {
    usecase "UC-1 Register"         as UC1
    usecase "UC-2 Provide parental consent" as UC2
    usecase "UC-3 Login"                    as UC3
    usecase "UC-16 Manage users"   as UC16
  }

  package "Dashboard" {
    usecase "UC-4 View completed projects"    as UC4
    usecase "UC-5 Start new project" as UC5
    usecase "UC-6 Resume project"    as UC6
  }

  package "Project" {
    usecase "UC-7 View day page"                as UC7
    usecase "UC-8 Interact with content"        as UC8
    usecase "UC-9 Fill forms"           as UC9
    usecase "UC-10 Execute calculations" as UC10
  }

  package "Reporting" {
    usecase "UC-11 Generate reports" as UC11
    usecase "UC-12 Export reports"   as UC12
  }

  package "Administration" {
    usecase "UC-13 Manage projects" as UC13
    usecase "UC-14 Manage components"   as UC14
    usecase "UC-15 Manage content"   as UC15
  }
}

Parent -down->  UC2
Kid    -- UC1
Kid    -- UC3
Kid    -- UC4
Kid    -- UC5
Kid    -- UC6
Kid    -- UC7
Kid    -- UC8
Kid    -- UC9
Kid    -- UC10
Kid    -- UC11
Kid    -- UC12

UC1 -right[hidden]-UC3
UC4 -right[hidden]-UC5
UC5 -right[hidden]-UC6

Admin  -- UC13
Admin  -- UC14
Admin  -- UC15
Admin  -- UC16

UC1  ..left..> UC2  : <<include>>
UC5  ..> UC7  : <<include>>
UC6  ..> UC7  : <<include>>
UC9  .right.> UC10 : <<include>>
UC11 .right.> UC12 : <<include>>
@enduml