---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd # the chart name on Artifact Hub
      version: 7.7.23 # (example) specify a pinned version
      sourceRef:
        kind: HelmRepository
        name: argocd # references the HelmRepository above
        namespace: argocd
  # If your cluster does not yet have the namespace, you can have Flux create it:
  install:
    createNamespace: true
  values:
    global:
      domain: "argocd.localhost"

    certificate:
      enabled: false

    crds:
      install: true

    configs:
      repositories:
        private-repo:
          url: git@github.com:dmr4eg/littlepm.git
          name: dnai-azure-git-repo
          type: git
          username: git
          # :D encoded password, but FIXME
          password: "YjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUNGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFnRUFyZmtjcWYyVkFvamt4UU5NWGdrLzByL0libVBlWm5ZV252ZDJHb2QxbEFVeE4vcldBUXJ0CjN1NlFvcjgwbGpsMlpyeG1kMi95Nk5meHZFT2dQbmttZVRManBzb05ONFRURXVJZ0ZVOWxGL1E2cGZIMVZsRTh3a1A3VGUKY2tqOGNKVkVKMDdiOSs3a1ZJNWN5NGhaU3p4c1dMcEc1VUNTdDR5dmpBM3crRnZDdEFmdDkwc2tDS0h0NWcvVERvbkl5RApVYVd1cCt5cmYycFBzVmNvcVZoYWJnMWx6ajdadGo1aURTeGl3UjRiU0w1L043ZjZEWXhoMk53TVBqMHN4bnNBR2xDRmFvCk1neEUvV3RGNTdIcnRvakRISlJFK2J3R3U2V3k1cFRCY3d5Z3JhZHNaOU1XNUJHb2ZDck04Ry94c2tmYzdDTzIxQW5iWG8KVUxpemJPNEJ3Nm1ValVpaHBqc0M2aVZtcExxSUViTEk4ZEhkR3FSeHRXa3RUSzZNSUJvYVk5U1JpM2tPakZZSG1ybnRvSworeTlaK1NnUXU1OGxHZjIrWng1L2I1TDRKOTVXTzVWZDBwY091NU8vbGJzcWRMbVZLTHBzWC9INjlFTTd5clkrT1ZkR1Z3CjBqbytYV3hEcFBaM05RVlpLNE91MmJwQkt6bDdCWnhUSi9ORWptYW1hNS9BbnV4aXpTa3JkTFhxUnIxT2toT2hkOFV2MkEKOEhRN3hJMEt6RW1rZndMU2tSWmFaeHlnRGZIVzNTdE5nZkdvOU8zSkpqbklrVm1GdnlJam9ieGNRVTBOWEJkVjhzUDZqQgpINzgvbXV4VFpBbU84NGEyVVM0WCtTQXpsYlZnbVg2N3VCZXY3aVZDWEVxenUrd2tSU1BYTjhNRE9oZUFLWFRTNXpDYk51Ck1BQUFkZzR1eHBTZUxzYVVrQUFBQUhjM05vTFhKellRQUFBZ0VBcmZrY3FmMlZBb2preFFOTVhnay8wci9JYm1QZVpuWVcKbnZkMkdvZDFsQVV4Ti9yV0FRcnQzdTZRb3I4MGxqbDJacnhtZDIveTZOZnh2RU9nUG5rbWVUTGpwc29OTjRUVEV1SWdGVQo5bEYvUTZwZkgxVmxFOHdrUDdUZWNrajhjSlZFSjA3YjkrN2tWSTVjeTRoWlN6eHNXTHBHNVVDU3Q0eXZqQTN3K0Z2Q3RBCmZ0OTBza0NLSHQ1Zy9URG9uSXlEVWFXdXAreXJmMnBQc1Zjb3FWaGFiZzFsemo3WnRqNWlEU3hpd1I0YlNMNS9ON2Y2RFkKeGgyTndNUGowc3huc0FHbENGYW9NZ3hFL1d0RjU3SHJ0b2pESEpSRStid0d1Nld5NXBUQmN3eWdyYWRzWjlNVzVCR29mQwpyTThHL3hza2ZjN0NPMjFBbmJYb1VMaXpiTzRCdzZtVWpVaWhwanNDNmlWbXBMcUlFYkxJOGRIZEdxUnh0V2t0VEs2TUlCCm9hWTlTUmkza09qRllIbXJudG9LK3k5WitTZ1F1NThsR2YyK1p4NS9iNUw0Sjk1V081VmQwcGNPdTVPL2xic3FkTG1WS0wKcHNYL0g2OUVNN3lyWStPVmRHVncwam8rWFd4RHBQWjNOUVZaSzRPdTJicEJLemw3Qlp4VEovTkVqbWFtYTUvQW51eGl6UwprcmRMWHFScjFPa2hPaGQ4VXYyQThIUTd4STBLekVta2Z3TFNrUlphWnh5Z0RmSFczU3ROZ2ZHbzlPM0pKam5Ja1ZtRnZ5Cklqb2J4Y1FVME5YQmRWOHNQNmpCSDc4L211eFRaQW1PODRhMlVTNFgrU0F6bGJWZ21YNjd1QmV2N2lWQ1hFcXp1K3drUlMKUFhOOE1ET2hlQUtYVFM1ekNiTnVNQUFBQURBUUFCQUFBQ0FRQ080VWpwVTVwTnVxQW9MYzFLYmM0OUI4VlU1RENEZGZpZQpGaDZwS3hjbHVoM3lHOUFtaXhOUlJCMEZqSU5qM1UyZ2twcVUvUnhDbnhlcHh1Q1VibXRxbnFEWkdwaEFRSllackIwdFkwCmRqcFBHRjJISGxzbEowT2VEcTJpcnM2a3AvS1JWZkxTYlNDWlVWSmsxbFovcytCSC9yUzdFNDFyc2Q5NjV2aEJBUnVuUDkKdndmWVhha1NNUkQyNEhRcUhqeTdrWmNmMHdBR1pRbU9YRWJJemdkMjJ3b0JtUnkwMEFjM1NuelFuaWxLVlNtbVdUTEViYwpidWs4cDZVME95dnRJV3lvcklMMmw1MFJoRWlsUVRxVmJ6ek8rL2FxSkFKam1uS1RiUmh6cEt0UjgyN1Uxa2kyaHNvWk1BCjJnYWsvV1c2N1ZRWCttSlhKRTduL01sZmJSbUVmWUgvU21NdzNSbWtYWkxIdlIrNmtLMUR5cStBMEg3S0FTaGZnYTA2dXMKSTBRL01RWmlXTm92TDRESkFJK2pRVWcydnBFU2h2UVFxay8zNjQwR2NsVmt4anhOYy9DekdMMlJGRG5vclJaOWJsZFl3bQpsZHlnT1BNUGdTdEtyNndEYUJud2pnRzBRelArcC9YOUtVUjQ2cGw1UWV1K3lyMVVxU1F4S0dQVlEyOGh4K3lFb1VVbW9sClcyZG9NUmNRcTJQaUtacEV5aGtGQ3lLV0RxWUZmMThkRkFlMG1NU0J6RTd6QUpEb0pRbEVHT2VucmcyWHRzTFBnYkttL1YKOThKS1FTT09oZDRVZkN1aVBtdnF3NGxFT0dWcmxVZzRvaG9tbFY4U25HS0lLMktCTTI0TnR0UWU4bnFaMmNseU1VUkxlKwpSSG40L1NkS2xFS00yU1ZFekFBUUFBQVFBRUc2blN1Sll0QzFwQzJFYU1LNVdsUGhseldXQndvcDB1V3VWTzI3ajhkZ29UCjh0M2o3c1p3b0R1MHdLbTltU0FYblNiZHo3M2pST3ZoTWZrZ285RzVhbkI3dkRjNWx3NEZRd05OeTJSemJMZjQ2SCtpV2IKYXV4eEhsVnZEbHNmSUhyYmw5eWhMeEM5c0dDNUNTN0RNbmdPMTZBSlBwdEI0UUdIZldGVHV3VlhhQXdPR3BKdC9NTzRXRQpGWS9Bcnh1eGZXbXRtNDZmNDdjWlBIcGk2Q0xPUE9WeGRpTkNldERLSFJWVzU3dGF2TUtDeklWRmVGbitRYmdhVzlUOGFkCms1ay9zZ2xGZnJIWHZMQ2E3MjJaL0xGemoxUFJaNkZHb0pHaW5takpQQ1NoWjY1VTJKa3hweHpWenNxS29MbHBkSW9EMFQKYTcrTXQveGN5dXlDdnZCT0FBQUJBUURjeFY5djVtcnZ2UGFjYllLWmI0SFh1WnM1U2d6KzBvNVZXOGFtaXFYMnNaUU8xcQoyMVBwZTFsaWtPTDM4Zlp0MjVKRmlHVFNuLytDdWRpRm9TWFo4VmJSNkxHUGhyLzNMcUkzeHp4c3lTdnI3VHdOd3ZnaTlJCkFla2hzcytwcG9jNTlvMU5hcnk3anBHaFFiTStlTGM2TkFUN3FzOHRNbU1rU2lNcDRYRUdOWHh4NXYySzFLcTJKL1l4ay8KdlpYTHJUa29ROE4xTHJ0dHBJUHhsZlU4NyszUWZZVjR3N1VScThhOGh2a3lQbHVLSXhhODRKWTBBWVBIVU5zUlMxY0FTQQoxak0wZnMwQ2p5eVJUdEhvbmdCbXh0UjdNdncraEw2K0RRalhMM0JjcmVIdlJ0NUViTjVVY3hBT0Jjd05yUFU4ZmFPMnl6CmU2TDNPS3A1YVRFdUJqQUFBQkFRREp2QVJqclk1a3l2ZUl0ZnpxdWFENTYxSmZhR0gzTStEQzZiaGNrWG1reXphaFVjQnMKTVd2cE1SWmFiZmk1dGFabVJxM2N0RkIrSUZxelNFSlVlWVVzNTdZRnM0WVJXZnBOaTk3enRLSDFUMDB4MlBiZVQ2RjJGVApNNCtxZEdkVHBrUXNCU1FjODljK3pZZFk4RmswZFJBSmlsd1ViSkI2WHdUcG5oOFpXN2I0b3BOMU5qbzdXWFFTdGJsQXc5Cm05QTArMXROYmt0NEFLWEFwK2pwNUE0MDh6KzlDMlJ4N3dGbC9LY3dIYUZHNytUQWQ4YzFkaU1GaHVsT002aEU3NkJmQ0EKM0JubllDMEsyR3loUml0a1FRZGlzaEkwZ05EUUMxYXo0N3JKdi9BRzVtY1RGUkgxZnRUVUswSS95dHpyQ3pyZUZZME9KaAptT012THYyb1Y5ZUJBQUFBSTJSdGNqUmxaMEJFWVcxcGNtTm9hV3R6TFUxaFkwSnZiMnN0UVdseUxteHZZMkZzQVFJREJBClVHQnc9PQo="
      params:
        server.insecure: true
      cm:
        admin.enabled: true
      secret:
        ## htpasswd -nbBC 10 "" "password" | tr -d ':\n' | sed 's/$2y/$2a/'
        argocdServerAdminPassword: "$2a$10$gKQEW.1kDyZUpFyRIXhEJ.RymGuHTDGwDGFf/.CXf/X2.lZ5r1ae2"

    server:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hostname: "argocd.localhost"
        tls: "false"
        extraTls: []
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      service:
        type: ClusterIP
  # valuesFrom:
  #   - kind: Secret
  #     name: argocd-repo-creds
  #     namespace: default
  #     valuesKey: password
  #     targetPath: configs.repositories.private-repo.password
