# https://artifacthub.io/packages/helm/cert-manager/cert-manager/1.17.1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10s
  targetNamespace: cert-manager
  chart:
    spec:
      interval: 10s
      chart: cert-manager
      version: "1.17.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  install:
    createNamespace: true
  values:
    installCRDs: true
    extraArgs:
      - "--dns01-recursive-nameservers-only"
      - "--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53"
