---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      interval: 10s
      version: "26.1.3" # Specify the desired version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicaCount: 1
    ingress:
      enabled: true
      ingressClassName: nginx # Specify your ingress class
      hostname: auth.app.little.pm
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging" # Example for cert-manager

