# https://artifacthub.io/packages/helm/bitnami/keycloak/24.5.2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  dependsOn:
    - name: ingress-nginx
  interval: 10s
  targetNamespace: keycloak
  releaseName: keycloak
  chart:
    spec:
      chart: ./bitnami/keycloak
      interval: 10s
      version: "24.5.2"
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 5m0s
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    # httpRelativePath: "/auth/"
    production: false
    # logging:
    #   output: default
    #   level: ALL
    auth:
      adminUser: "admin1342"
      adminPassword: "admin1342"
      # existingSecret: "keycloak-credentials"
      # passwordSecretKey: "password"

    postgresql:
      enabled: true
      auth:
        username: bn_keycloak
        database: bitnami_keycloak
        password: "superpassword"
        # existingSecret: "postgres-credentials"
        # secretKeys:
        #   userPasswordKey: "password"

    ingress:
      enabled: true
      ingressClassName: nginx
      tls: false
      hostname: auth.app.little.pm
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/acme-challenge-type: "http01"

    adminIngress:
      enabled: true
      hostname: admin.auth.app.little.pm
      ingressClassName: nginx
      tls: false
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        ingress.kubernetes.io/ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/acme-challenge-type: "http01"
