apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-ingress.yaml
  - cert-manager.yaml
  # - kube-dashboard.yaml
  # - keycloak.yaml
  # - argocd.yaml
  # - prometheus-grafana.yaml
