---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: ingress-nginx
  chart:
    spec:
      interval: 10s
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      ingressClass: nginx-external
      ingressClassByName: true
      ingressClassResource:
        name: "nginx"
        enabled: true
        default: true
