# https://artifacthub.io/packages/helm/bitnami/redis/20.12.1
---
# apiVersion: helm.toolkit.fluxcd.io/v2
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  targetNamespace: redis
  releaseName: redis
  interval: 10s
  chart:
    spec:
      # chart: redis
      chart: ./bitnami/redis
      version: "20.12.1"
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: flux-system
      interval: 10s
  install:
    crds: CreateReplace
    createNamespace: true
  values:
    auth:
      enabled: false
      # password: "my-custom-redis-password"
