---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 1m
  url: https://argoproj.github.io/argo-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd # the chart name on Artifact Hub
      version: 7.7.23 # (example) specify a pinned version
      sourceRef:
        kind: HelmRepository
        name: argocd # references the HelmRepository above
        namespace: argocd
  # If your cluster does not yet have the namespace, you can have Flux create it:
  install:
    createNamespace: true
  values:
    global:
      domain: "argocd.localhost"

    certificate:
      enabled: false

    crds:
      install: true

    configs:
      repositories:
        private-repo:
          url: git@github.com:dmr4eg/littlepm.git
          name: azure-git-repo
          type: git
          username: git
          # :D encoded password, but FIXME
          password: "="
      params:
        server.insecure: true
      cm:
        admin.enabled: true
      secret:
        ## htpasswd -nbBC 10 "" "password" | tr -d ':\n' | sed 's/$2y/$2a/'
        argocdServerAdminPassword: "$2a$10$gKQEW.1kDyZUpFyRIXhEJ.RymGuHTDGwDGFf/.CXf/X2.lZ5r1ae2"

    server:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hostname: "argocd.localhost"
        tls: "false"
        extraTls: []
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      service:
        type: ClusterIP
  # valuesFrom:
  #   - kind: Secret
  #     name: argocd-repo-creds
  #     namespace: default
  #     valuesKey: password
  #     targetPath: configs.repositories.private-repo.password
