apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base

namespace: staging
# patches:
#   - path: staging-values.yaml
#     target:
#       kind: HelmRelease
