---
######## Repository Configuration ########
repo_url: "https://github.com/dmr4eg/littlepm.git"

######## K8s Cluster Configuration ########
cluster_name: littlepm-kind
control_nodes: 1
worker_nodes: 2

######## Ingress Configuration ########
ingress_nginx_namespace: "ingress-nginx"
ingress_nginx_release: "ingress-nginx"
ingress_nginx_chart: "ingress-nginx/ingress-nginx"
ingress_nginx_chart_version: "4.11.2"

######## ArgoCD Configuration ########
argocd_namespace: argocd
argocd_server: argocd-server
argocd_server_port: 80

######## Environment Configuration ########
charts:
  - name: finances-service
    path: "infrastructure/helm/charts/finances-service"
  - name: project-conf-service
    path: "infrastructure/helm/charts/project-conf-service"
  - name: report-service
    path: "infrastructure/helm/charts/report-service"
  - name: task-service
    path: "infrastructure/helm/charts/task-service"
  - name: user-service
    path: "infrastructure/helm/charts/user-service"

######### Postgres Chart Configuration ########"
pg_chart_name: "postgres-db"
pg_chart_version: "16.4.14"
pg_release_name: "bitnami/postgresql"
pg_values_file: "postgres-values.yaml"
pg_chart_path: "infrastructure/helm/values"
