---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course
spec:
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: docker.io/nginx:stable
          # image: ghcr.io/dmr4eg/littlepm-course-service:latest
          env:
            - name: SOME_ENV_VAR
              value: some-value
          envFrom:
            - secretRef:
                name: database-credentials
            - configMapRef:
                name: be
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
              # containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  selector:
    app: course
  ports:
    - port: 80
      name: http
      targetPort: http
