# https://artifacthub.io/packages/helm/bitnami/keycloak/24.5.8
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: keycloak
  releaseName: keycloak
  chart:
    spec:
      # chart: keycloak
      chart: ./bitnami/keycloak
      interval: 10s
      version: "24.5.8"
      sourceRef:
        # kind: HelmRepository
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 20m0s
  values:
    replicaCount: 1

    proxy: edge
    proxyHeaders: xforwarded

    startupProbe:
      enabled: true # Enabled to prevent liveness probe from killing pod too early
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30 # Total startup time: 30 x 10 = 300 seconds
      successThreshold: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 120 # Increased delay to allow app to become ready
      periodSeconds: 20
      timeoutSeconds: 5 # Increased to allow more time per check
      failureThreshold: 30 # More failures allowed before marking as not ready
      successThreshold: 1

    livenessProbe:
      enabled: true
      initialDelaySeconds: 360 # Delayed to ensure app has fully started
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 5
      successThreshold: 1

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

    production: false

    postgresql:
      enabled: true
      auth:
        username: bn_keycloak
        database: bitnami_keycloak
        password: bn_keycloak_password

    auth:
      adminUser: admin1342
      adminPassword: admin1342

    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: auth.app.little.pm
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        # cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/acme-challenge-type: "http01"

    adminIngress:
      enabled: false
