# keycloak HelmRelease – fixed
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
  interval: 10m0s
  targetNamespace: keycloak
  releaseName: keycloak
  chart:
    spec:
      chart: ./bitnami/keycloak
      version: 24.5.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  install:
    createNamespace: true
    crds: CreateReplace
    timeout: 20m0s
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: "1"
        memory: 1.5Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 50Mi

    production: false

    postgresql:
      enabled: true
      auth:
        username: bn_keycloak
        password: bn_keycloak
        postgresPassword: bn_keycloak
        database: bitnami_keycloak

    auth:
      adminUser: admin1342
      adminPassword: admin1342

    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: auth.app.little.pm
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/acme-challenge-type: "http01"

    adminIngress:
      enabled: false
