# https://artifacthub.io/packages/helm/bitnami/keycloak/24.5.8
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10s
  targetNamespace: keycloak
  releaseName: keycloak
  chart:
    spec:
      # chart: keycloak
      chart: ./bitnami/keycloak
      interval: 10s
      version: "24.5.8"
      sourceRef:
        # kind: HelmRepository
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 1.5
        memory: 1.5Gi
        ephemeral-storage: 2Gi
      requests:
        cpu: 1
        memory: 768Mi

    production: false

    postgresql:
      enabled: false

    externalDatabase:
      host: postgres-postgresql.postgres.svc.cluster.local # service created by your other release
      port: 5432
      database: postgres
      user: bn_keycloak
      password: bn_keycloak # or use externalDatabase.existingSecret

    auth:
      adminUser: admin1342
      adminPassword: admin1342

    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: auth.app.little.pm
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/acme-challenge-type: "http01"

    adminIngress:
      enabled: false
