# https://artifacthub.io/packages/helm/bitnami/postgresql/16.6.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.12.12"
      sourceRef:
        kind: GitRepository
        name: oauth2-proxy
        namespace: flux-system
  interval: 3m
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 20m0s
    remediation:
      retries: 3
