# https://artifacthub.io/packages/helm/bitnami/postgresql/16.6.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  releaseName: postgres
  chart:
    spec:
      # chart: postgresql
      chart: postgresql
      version: "16.6.3"
      sourceRef:
        kind: GitRepository
        name: bitnami
        namespace: flux-system
  interval: 3m
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 20m0s
    remediation:
      retries: 3
  values:
    global:
      postgres:
        auth:
          username: "postgres"
          existingSecret: "database-credentials"
          secretKeys:
            adminPasswordKey: "postgres_PASSWORD"
            userPasswordKey: "postgres_PASSWORD"
    auth:
      enablePostgresUser: true
      username: "postgres"
      existingSecret: "database-credentials"
      secretKeys:
        adminPasswordKey: "postgres_PASSWORD"
        userPasswordKey: "postgres_PASSWORD"

    primary:
      initdb:
        scripts:
          initdb.sql: |
            CREATE DATABASE courses;
            CREATE DATABASE content;
