---
- name: Add ArgoCD helm repo
  kubernetes.core.helm_repository:
    name: "argocd"
    repo_url: "https://argoproj.github.io/argo-helm"
    state: present
  tags:
    - add-argocd-helm-repo

- name: Render ArgoCD values file from template
  template:
    src: "templates/argocd-values.yml.j2"
    dest: "/tmp/argocd-values.yml"
  tags:
    - template-argocd-values

- name: Install/Upgrade ArgoCD using Helm
  kubernetes.core.helm:
    name: "argocd"         
    chart_ref: "argo/argo-cd"
    create_namespace: true
    chart_version: "{{ argocd_chart_version }}"
    release_namespace: "{{ argocd_namespace }}"
    values_files:
      - "/tmp/argocd-values.yml" 
    state: present
  tags:
    - install-argocd

- name: ArgoCD setup has been finished
  debug:
    msg: "ArgoCD in {{ argocd_namespace }} namespace has been installed successfully"
  tags:
    - argocd-setup-finished