---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-keycloak
  namespace: flux-system
spec:
  interval: 15m
  url: oci://registry-1.docker.io/bitnamicharts/keycloak
