---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/bitnami/charts
  ref:
    branch: main
