---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m
  url: https://oauth2-proxy.github.io/manifests
  ref:
    branch: main
